spring.application.name=authentication-security
spring.datasource.url=jdbc:mysql://localhost:3306/auth_security
spring.datasource.username= username
spring.datasource.password= password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# JWT Configuration
jwt.secret=MySecretKeyForJwtAuthenticationProject2026SpringBootSecurity
jwt.expiration=86400000
